const rawUser = 
[
  {
    "profession": "teacher",
    "first_name": "Arjun",
    "last_name": "Malhotra",
    "email": "arjun.malhotra@example.com",
    "education": "Ph.D Biochemistry",
    "contact": "9123456780",
    "password": "$2b$10$y40nKF5iiii0mV0sss5z4oM1m5pIzzzYmmmslxmlxml8j5tuvDv6T6",
    "confirm_password": "$2b$10$y40nKF5iiii0mV0sss5z4oM1m5pIzzzYmmmslxmlxml8j5tuvDv6T6",
    "displayName": "Dr. Arjun M.",
    "dob": "1978-12-22",
    "gender": "Male",
    "address": {
      "country": "IN",
      "state": "SK",
      "city": "Gangtok"
    },
    "subject": ["Biochemistry", "Molecular Biology"],
    "classname": "Post Graduate",
    "school": "Sikkim University",
    "board": "UGC",
    "twitter": "arjun_biochem",
    "facebook": "fb.com/arjun.malhotra",
    "instagram": "insta.com/biochemwithArjun",
    "youtube": "youtube.com/molecularworld",
    "github": "github.com/arjunmalhotra",
    "linkedin": "linkedin.com/in/arjunmalhotra",
    "bio": "Biochemistry professor with expertise in protein structure and drug development research.",
    "nearestLocation": "MG Marg",
    "teaching_method": "Online",
    "status": "active"
  },
  {
    "profession": "teacher",
    "first_name": "Divya",
    "last_name": "Chakraborty",
    "email": "divya.chakraborty@example.com",
    "education": "M.A Sociology",
    "contact": "8234567801",
    "password": "$2b$10$z51oLG6jjjj1nW1ttt6z5pN2n6qJzzzZnnnsmynoynp9k6tuvEw7U7",
    "confirm_password": "$2b$10$z51oLG6jjjj1nW1ttt6z5pN2n6qJzzzZnnnsmynoynp9k6tuvEw7U7",
    "displayName": "Divya C.",
    "dob": "1995-04-18",
    "gender": "Female",
    "address": {
      "country": "IN",
      "state": "TR",
      "city": "Agartala"
    },
    "subject": ["Sociology", "Social Research"],
    "classname": "Undergraduate",
    "school": "Tripura University",
    "board": "UGC",
    "twitter": "divya_sociology",
    "facebook": "fb.com/divya.chakraborty",
    "instagram": "insta.com/sociologywithDivya",
    "youtube": "youtube.com/societyandculture",
    "github": "github.com/divyachakraborty",
    "linkedin": "linkedin.com/in/divyachakraborty",
    "bio": "Sociology lecturer focusing on gender studies and rural development issues.",
    "nearestLocation": "Battala",
    "teaching_method": "Hybrid",
    "status": "active"
  },
  {
    "profession": "teacher",
    "first_name": "Harish",
    "last_name": "Chand",
    "email": "harish.chand@example.com",
    "education": "M.A Philosophy",
    "contact": "7345678912",
    "password": "$2b$10$a62pMH7kkkk2oX2uuu7z6qO3o7rKzzzAoootypozypq0l7tuvFx8V8",
    "confirm_password": "$2b$10$a62pMH7kkkk2oX2uuu7z6qO3o7rKzzzAoootypozypq0l7tuvFx8V8",
    "displayName": "Harish C.",
    "dob": "1981-07-06",
    "gender": "Male",
    "address": {
      "country": "IN",
      "state": "JK",
      "city": "Srinagar"
    },
    "subject": ["Philosophy", "Ethics"],
    "classname": "Class 11-12",
    "school": "Burn Hall School",
    "board": "JKBOSE",
    "twitter": "harish_philosophy",
    "facebook": "fb.com/harish.chand",
    "instagram": "insta.com/philosophywithHarish",
    "youtube": "youtube.com/thinkingdeep",
    "github": "github.com/harishchand",
    "linkedin": "linkedin.com/in/harishchand",
    "bio": "Philosophy teacher specializing in Indian philosophical traditions and moral reasoning.",
    "nearestLocation": "Dal Lake",
    "teaching_method": "Offline",
    "status": "active"
  },
  {
    "profession": "teacher",
    "first_name": "Smita",
    "last_name": "Bhosle",
    "email": "smita.bhosle@example.com",
    "education": "M.Sc Botany",
    "contact": "6456789023",
    "password": "$2b$10$b73qNI8llll3pY3vvv8z7rP4p8sLzzzBpppuzqpazqr1m8tuvGy9W9",
    "confirm_password": "$2b$10$b73qNI8llll3pY3vvv8z7rP4p8sLzzzBpppuzqpazqr1m8tuvGy9W9",
    "displayName": "Smita B.",
    "dob": "1987-09-14",
    "gender": "Female",
    "address": {
      "country": "IN",
      "state": "GA",
      "city": "Panaji"
    },
    "subject": ["Botany", "Plant Ecology"],
    "classname": "Class 11-12",
    "school": "Goa Board of Secondary Education",
    "board": "GBSHSE",
    "twitter": "smita_botany",
    "facebook": "fb.com/smita.bhosle",
    "instagram": "insta.com/botanywithSmita",
    "youtube": "youtube.com/plantworld",
    "github": "github.com/smitabhosle",
    "linkedin": "linkedin.com/in/smitabhosle",
    "bio": "Botany teacher passionate about marine plant life and coastal ecosystem conservation.",
    "nearestLocation": "Miramar Beach",
    "teaching_method": "Hybrid",
    "status": "active"
  },
  {
    "profession": "teacher",
    "first_name": "Tarun",
    "last_name": "Singh",
    "email": "tarun.singh@example.com",
    "education": "MBA Finance",
    "contact": "5567890134",
    "password": "$2b$10$c84rOJ9mmmm4qZ4www9z8sQ5q9tMzzzCqqqvArqbArb2n9tuvHz0X0",
    "confirm_password": "$2b$10$c84rOJ9mmmm4qZ4www9z8sQ5q9tMzzzCqqqvArqbArb2n9tuvHz0X0",
    "displayName": "Tarun S.",
    "dob": "1986-11-28",
    "gender": "Male",
    "address": {
      "country": "IN",
      "state": "NL",
      "city": "Kohima"
    },
    "subject": ["Business Studies", "Financial Management"],
    "classname": "Class 12",
    "school": "Little Flower Higher Secondary School",
    "board": "NBSE",
    "twitter": "tarun_business",
    "facebook": "fb.com/tarun.singh",
    "instagram": "insta.com/businesswithTarun",
    "youtube": "youtube.com/financialwisdom",
    "github": "github.com/tarunsingh",
    "linkedin": "linkedin.com/in/tarunsingh",
    "bio": "Business studies teacher with corporate banking experience and financial planning expertise.",
    "nearestLocation": "Dimapur Road",
    "teaching_method": "Online",
    "status": "active"
  },
  {
    "profession": "teacher",
    "first_name": "Rekha",
    "last_name": "Pandey",
    "email": "rekha.pandey@example.com",
    "education": "M.A Political Science",
    "contact": "4678901245",
    "password": "$2b$10$d95sPK0nnnn5rA5xxx0z9tR6r0uNzzzDrrrwBsrcBsr3o0tuvI01Y1",
    "confirm_password": "$2b$10$d95sPK0nnnn5rA5xxx0z9tR6r0uNzzzDrrrwBsrcBsr3o0tuvI01Y1",
    "displayName": "Rekha P.",
    "dob": "1989-01-10",
    "gender": "Female",
    "address": {
      "country": "IN",
      "state": "MN",
      "city": "Imphal"
    },
    "subject": ["Political Science", "Public Administration"],
    "classname": "Class 11",
    "school": "Manipur University",
    "board": "COHSEM",
    "twitter": "rekha_polisci",
    "facebook": "fb.com/rekha.pandey",
    "instagram": "insta.com/politicswithRekha",
    "youtube": "youtube.com/governance101",
    "github": "github.com/rekhapandey",
    "linkedin": "linkedin.com/in/rekhapandey",
    "bio": "Political science teacher focusing on Indian governance, democracy, and constitutional studies.",
    "nearestLocation": "Keishampat",
    "teaching_method": "Offline",
    "status": "active"
  },
  {
    "profession": "teacher",
    "first_name": "Ashok",
    "last_name": "Tripathi",
    "email": "ashok.tripathi@example.com",
    "education": "M.Tech Electronics",
    "contact": "3789012356",
    "password": "$2b$10$e06tQL1oooo6sB6yyy1z0uS7s1vOzzzEssswCtscCts4p1tuvJ12Z2",
    "confirm_password": "$2b$10$e06tQL1oooo6sB6yyy1z0uS7s1vOzzzEssswCtscCts4p1tuvJ12Z2",
    "displayName": "Ashok T.",
    "dob": "1984-05-03",
    "gender": "Male",
    "address": {
      "country": "IN",
      "state": "MZ",
      "city": "Aizawl"
    },
    "subject": ["Electronics", "Digital Systems"],
    "classname": "Diploma",
    "school": "Mizoram Institute of Technology",
    "board": "MBSE",
    "twitter": "ashok_electronics",
    "facebook": "fb.com/ashok.tripathi",
    "instagram": "insta.com/electronicswithAshok",
    "youtube": "youtube.com/circuitsexplained",
    "github": "github.com/ashoktripathi",
    "linkedin": "linkedin.com/in/ashoktripathi",
    "bio": "Electronics engineering teacher with expertise in embedded systems and IoT applications.",
    "nearestLocation": "Zarkawt",
    "teaching_method": "Hybrid",
    "status": "active"
  },
  {
    "profession": "teacher",
    "first_name": "Nandini",
    "last_name": "Rao",
    "email": "nandini.rao@example.com",
    "education": "M.A Anthropology",
    "contact": "2890123467",
    "password": "$2b$10$f17uRM2pppp7tC7zzz2z1vT8t2wPzzzFtttxDutdDut5q2tuvK23A3",
    "confirm_password": "$2b$10$f17uRM2pppp7tC7zzz2z1vT8t2wPzzzFtttxDutdDut5q2tuvK23A3",
    "displayName": "Nandini R.",
    "dob": "1992-08-19",
    "gender": "Female",
    "address": {
      "country": "IN",
      "state": "AR",
      "city": "Itanagar"
    },
    "subject": ["Anthropology", "Cultural Studies"],
    "classname": "Undergraduate",
    "school": "Rajiv Gandhi University",
    "board": "UGC",
    "twitter": "nandini_anthropology",
    "facebook": "fb.com/nandini.rao",
    "instagram": "insta.com/culturewithNandini",
    "youtube": "youtube.com/tribalstudies",
    "github": "github.com/nandinirao",
    "linkedin": "linkedin.com/in/nandinirao",
    "bio": "Anthropology lecturer specializing in Northeast Indian tribal cultures and traditions.",
    "nearestLocation": "Naharlagun",
    "teaching_method": "Online",
    "status": "active"
  },
  {
    "profession": "teacher",
    "first_name": "Suresh",
    "last_name": "Reddy",
    "email": "suresh.reddy@example.com",
    "education": "M.Sc Geology",
    "contact": "1901234578",
    "password": "$2b$10$g28vSN3qqqq8uD8aaa3z2wU9u3xRzzzGuuuyEvueEvu6r3tuvL34B4",
    "confirm_password": "$2b$10$g28vSN3qqqq8uD8aaa3z2wU9u3xRzzzGuuuyEvueEvu6r3tuvL34B4",
    "displayName": "Suresh R.",
    "dob": "1983-02-26",
    "gender": "Male",
    "address": {
      "country": "IN",
      "state": "ML",
      "city": "Shillong"
    },
    "subject": ["Geology", "Environmental Science"],
    "classname": "Class 11-12",
    "school": "North-Eastern Hill University",
    "board": "MBOSE",
    "twitter": "suresh_geology",
    "facebook": "fb.com/suresh.reddy",
    "instagram": "insta.com/geologywithSuresh",
    "youtube": "youtube.com/earthsciences",
    "github": "github.com/sureshreddy",
    "linkedin": "linkedin.com/in/sureshreddy",
    "bio": "Geology teacher focusing on mineral exploration and environmental impact assessment.",
    "nearestLocation": "Police Bazaar",
    "teaching_method": "Hybrid",
    "status": "active"
  },
  {
    "profession": "teacher",
    "first_name": "Pallavi",
    "last_name": "Jain",
    "email": "pallavi.jain@example.com",
    "education": "M.A Journalism",
    "contact": "0912345689",
    "password": "$2b$10$h39wTO4rrrr9vE9bbb4z3xV0v4yRzzzHvvvzFwvfFwv7s4tuvM45C5",
    "confirm_password": "$2b$10$h39wTO4rrrr9vE9bbb4z3xV0v4yRzzzHvvvzFwvfFwv7s4tuvM45C5",
    "displayName": "Pallavi J.",
    "dob": "1991-06-12",
    "gender": "Female",
    "address": {
      "country": "IN",
      "state": "CT",
      "city": "Raipur"
    },
    "subject": ["Mass Communication", "Media Studies"],
    "classname": "Class 11-12",
    "school": "Pt. Ravishankar Shukla University",
    "board": "CGBSE",
    "twitter": "pallavi_media",
    "facebook": "fb.com/pallavi.jain",
    "instagram": "insta.com/mediawithPallavi",
    "youtube": "youtube.com/journalismbasics",
    "github": "github.com/pallavijain",
    "linkedin": "linkedin.com/in/pallavijain",
    "bio": "Mass communication teacher with newsroom experience in print and digital media.",
    "nearestLocation": "Shankar Nagar",
    "teaching_method": "Online",
    "status": "active"
  },
  {
    "profession": "teacher",
    "first_name": "Bharat",
    "last_name": "Sinha",
    "email": "bharat.sinha@example.com",
    "education": "M.Sc Forestry",
    "contact": "9823456790",
    "password": "$2b$10$i40xUP5ssss0wF0ccc5z4yW0w5zSzzzIwwwAGxwgGxw8t5tuvN56D6",
    "confirm_password": "$2b$10$i40xUP5ssss0wF0ccc5z4yW0w5zSzzzIwwwAGxwgGxw8t5tuvN56D6",
    "displayName": "Bharat S.",
    "dob": "1985-12-07",
    "gender": "Male",
    "address": {
      "country": "IN",
      "state": "UT",
      "city": "Dehradun"
    },
    "subject": ["Forestry", "Wildlife Management"],
    "classname": "Diploma",
    "school": "Forest Research Institute",
    "board": "UBSE",
    "twitter": "bharat_forestry",
    "facebook": "fb.com/bharat.sinha",
    "instagram": "insta.com/forestrywithBharat",
    "youtube": "youtube.com/wildlifeconservation",
    "github": "github.com/bharatsinha",
    "linkedin": "linkedin.com/in/bharatsinha",
    "bio": "Forestry expert teaching sustainable forest management and wildlife conservation practices.",
    "nearestLocation": "Rajpur Road",
    "teaching_method": "Offline",
    "status": "active"
  },
  {
    "profession": "teacher",
    "first_name": "Kavitha",
    "last_name": "Krishnan",
    "email": "kavitha.krishnan@example.com",
    "education": "M.Pharm Pharmacology",
    "contact": "8734567801",
    "password": "$2b$10$j51yVQ6tttt1xG1ddd6z5zX0z6aTzzzJzzz0HyxhHyx9u6tuvO67E7",
    "confirm_password": "$2b$10$j51yVQ6tttt1xG1ddd6z5zX0z6aTzzzJzzz0HyxhHyx9u6tuvO67E7",
    "displayName": "Kavitha K.",
    "dob": "1988-03-15",
    "gender": "Female",
    "address": {
      "country": "IN",
      "state": "PY",
      "city": "Puducherry"
    },
    "subject": ["Pharmacology", "Drug Development"],
    "classname": "Post Graduate",
    "school": "JIPMER",
    "board": "UGC",
    "twitter": "kavitha_pharma",
    "facebook": "fb.com/kavitha.krishnan",
    "instagram": "insta.com/pharmawithKavitha",
    "youtube": "youtube.com/drugscience",
    "github": "github.com/kavithakrishnan",
    "linkedin": "linkedin.com/in/kavithakrishnan",
    "bio": "Pharmacology professor researching traditional medicine and modern drug interactions.",
    "nearestLocation": "French Quarter",
    "teaching_method": "Hybrid",
    "status": "active"
  },
  {
    "profession": "teacher",
    "first_name": "Rohit",
    "last_name": "Chauhan",
    "email": "rohit.chauhan@example.com",
    "education": "M.A Linguistics",
    "contact": "7645678912",
    "password": "$2b$10$k62zWR7uuuu2yH2eee7z6aY0a7bUzzzKaaaBIzybIzy0v7tuvP78F8",
    "confirm_password": "$2b$10$k62zWR7uuuu2yH2eee7z6aY0a7bUzzzKaaaBIzybIzy0v7tuvP78F8",
    "displayName": "Rohit C.",
    "dob": "1990-10-21",
    "gender": "Male",
    "address": {
      "country": "IN",
      "state": "LD",
      "city": "Leh"
    },
    "subject": ["Linguistics", "Language Studies"],
    "classname": "Undergraduate",
    "school": "University of Ladakh",
    "board": "UGC",
    "twitter": "rohit_linguistics",
    "facebook": "fb.com/rohit.chauhan",
    "instagram": "insta.com/languageswithRohit",
    "youtube": "youtube.com/linguisticslab",
    "github": "github.com/rohitchauhan",
    "linkedin": "linkedin.com/in/rohitchauhan",
    "bio": "Linguistics professor specializing in Tibetan languages and endangered language documentation.",
    "nearestLocation": "Main Bazaar",
    "teaching_method": "Online",
    "status": "active"
  },
  {
    "profession": "teacher",
    "first_name": "Swati",
    "last_name": "Gupta",
    "email": "swati.gupta@example.com",
    "education": "M.Sc Microbiology",
    "contact": "6556789023",
    "password": "$2b$10$l73aXS8vvvv3zI3fff8z7bZ0b8cVzzzLbbbCJazcJaz1w8tuvQ89G9",
    "confirm_password": "$2b$10$l73aXS8vvvv3zI3fff8z7bZ0b8cVzzzLbbbCJazcJaz1w8tuvQ89G9",
    "displayName": "Swati G.",
    "dob": "1994-01-04",
    "gender": "Female",
    "address": {
      "country": "IN",
      "state": "DN",
      "city": "Silvassa"
    },
    "subject": ["Microbiology", "Medical Laboratory"],
    "classname": "Class 11-12",
    "school": "Vivekananda School",
    "board": "CBSE",
    "twitter": "swati_microbiology",
    "facebook": "fb.com/swati.gupta",
    "instagram": "insta.com/microbewithSwati",
    "youtube": "youtube.com/microworld",
    "github": "github.com/swatigupta",
    "linkedin": "linkedin.com/in/swatigupta",
    "bio": "Microbiology teacher focused on infectious disease research and laboratory techniques.",
    "nearestLocation": "Khanvel",
    "teaching_method": "Hybrid",
    "status": "active"
  },
  {
    "profession": "teacher",
    "first_name": "Mahesh",
    "last_name": "Joshi",
    "email": "mahesh.joshi@example.com",
    "education": "M.A Literature",
    "contact": "5467890134",
    "password": "$2b$10$m84bYT9wwww4aJ4ggg4z8cA0c9dWzzzMccczKbadKba2x9tuvR90H0",
    "confirm_password": "$2b$10$m84bYT9wwww4aJ4ggg4z8cA0c9dWzzzMccczKbadKba2x9tuvR90H0",
    "displayName": "Mahesh J.",
    "dob": "1987-07-17",
    "gender": "Male",
    "address": {
      "country": "IN",
      "state": "DD",
      "city": "Daman"
    },
    "subject": ["Literature", "Comparative Literature"],
    "classname": "Class 9-10",
    "school": "Shantilal Shah Government School",
    "board": "CBSE",
    "twitter": "mahesh_literature",
    "facebook": "fb.com/mahesh.joshi",
    "instagram": "insta.com/literaturewithMahesh",
    "youtube": "youtube.com/worldliterature",
    "github": "github.com/maheshjoshi",
    "linkedin": "linkedin.com/in/maheshjoshi",
    "bio": "Literature teacher exploring world classics and promoting cross-cultural literary understanding.",
    "nearestLocation": "Nani Daman",
    "teaching_method": "Offline",
    "status": "active"
  },
  {
    "profession": "teacher",
    "first_name": "Shilpa",
    "last_name": "Kaur",
    "email": "shilpa.kaur@example.com",
    "education": "M.Sc Food Technology",
    "contact": "4378901245",
    "password": "$2b$10$n95cZU0xxxx5bK5hhh5z9dB0d0eXzzzNddddLcbeKbe3y0tuvS01I1",
    "confirm_password": "$2b$10$n95cZU0xxxx5bK5hhh5z9dB0d0eXzzzNddddLcbeKbe3y0tuvS01I1",
    "displayName": "Shilpa K.",
    "dob": "1989-05-23",
    "gender": "Female",
    "address": {
      "country": "IN",
      "state": "CH",
      "city": "Chandigarh"
    },
    "subject": ["Food Technology", "Nutrition Science"],
    "classname": "Diploma",
    "school": "Institute of Hotel Management",
    "board": "NCHMCT",
    "twitter": "shilpa_foodtech",
    "facebook": "fb.com/shilpa.kaur",
    "instagram": "insta.com/foodtechwithShilpa",
    "youtube": "youtube.com/foodscience101",
    "github": "github.com/shilpakaur",
    "linkedin": "linkedin.com/in/shilpakaur",
    "bio": "Food technology expert teaching food safety, processing, and nutritional enhancement techniques.",
    "nearestLocation": "Sector 22",
    "teaching_method": "Hybrid",
    "status": "active"
  },
  {
    "profession": "teacher",
    "first_name": "Vinod",
    "last_name": "Kumar",
    "email": "vinod.kumar@example.com",
    "education": "M.A International Relations",
    "contact": "3289012356",
    "password": "$2b$10$o06dAV1yyyy6cL6iii6z0eC0e1fYzzzOeeeeMdcfMcf4z1tuvT12J2",
    "confirm_password": "$2b$10$o06dAV1yyyy6cL6iii6z0eC0e1fYzzzOeeeeMdcfMcf4z1tuvT12J2",
    "displayName": "Vinod K.",
    "dob": "1982-09-11",
    "gender": "Male",
    "address": {
      "country": "IN",
      "state": "DL",
      "city": "New Delhi"
    },
    "subject": ["International Relations", "Global Politics"],
    "classname": "Post Graduate",
    "school": "Jawaharlal Nehru University",
    "board": "UGC",
    "twitter": "vinod_intlrelations",
    "facebook": "fb.com/vinod.kumar",
    "instagram": "insta.com/globalaffairswithVinod",
    "youtube": "youtube.com/worldpolitics",
    "github": "github.com/vinodkumar",
    "linkedin": "linkedin.com/in/vinodkumar",
    "bio": "International relations professor analyzing global diplomacy and foreign policy strategies.",
    "nearestLocation": "Munirka",
    "teaching_method": "Online",
    "status": "active"
  },
  {
    "profession": "teacher",
    "first_name": "Anita",
    "last_name": "Sharma",
    "email": "anita.sharma@example.com",
    "education": "M.Ed Special Education",
    "contact": "2190123467",
    "password": "$2b$10$p17eBW2zzzz7dM7jjj7z1fD0f2gZzzzPfffNegehNeg5a2tuvU23K3",
    "confirm_password": "$2b$10$p17eBW2zzzz7dM7jjj7z1fD0f2gZzzzPfffNegehNeg5a2tuvU23K3",
    "displayName": "Anita S.",
    "dob": "1986-11-08",
    "gender": "Female",
    "address": {
      "country": "IN",
      "state": "BR",
      "city": "Patna"
    },
    "subject": ["Special Education", "Learning Disabilities"],
    "classname": "All Levels",
    "school": "Patna University",
    "board": "UGC",
    "twitter": "anita_specialed",
    "facebook": "fb.com/anita.sharma",
    "instagram": "insta.com/specialedwithAnita",
    "youtube": "youtube.com/inclusivelearning",
    "github": "github.com/anitasharma",
    "linkedin": "linkedin.com/in/anitasharma",
    "bio": "Special education teacher dedicated to inclusive learning and supporting children with disabilities.",
    "nearestLocation": "Boring Road",
    "teaching_method": "Offline",
    "status": "active"
  },
  {
    "profession": "teacher",
    "first_name": "Deepesh",
    "last_name": "Agrawal",
    "email": "deepesh.agrawal@example.com",
    "education": "M.Sc Statistics",
    "contact": "1012345678",
    "password": "$2b$10$q28fCX3aaaa8eN8kkk8z2gE0g3hAzzzQggggOfhiOfh6b3tuvV34L4",
    "confirm_password": "$2b$10$q28fCX3aaaa8eN8kkk8z2gE0g3hAzzzQggggOfhiOfh6b3tuvV34L4",
    "displayName": "Deepesh A.",
    "dob": "1991-04-02",
    "gender": "Male",
    "address": {
      "country": "IN",
      "state": "RJ",
      "city": "Udaipur"
    },
    "subject": ["Statistics", "Data Analysis"],
    "classname": "Class 11-12",
    "school": "Maharana Mewar Public School",
    "board": "RBSE",
    "twitter": "deepesh_stats",
    "facebook": "fb.com/deepesh.agrawal",
    "instagram": "insta.com/statswithDeepesh",
    "youtube": "youtube.com/datainsights",
    "github": "github.com/deepeshagrawal",
    "linkedin": "linkedin.com/in/deepeshagrawal",
    "bio": "Statistics teacher specializing in data visualization and predictive analytics methods.",
    "nearestLocation": "City Palace",
    "teaching_method": "Hybrid",
    "status": "active"
  }
]

module.exports = rawUser
